class ConvertFromThreeToFourByteUnicode < ActiveRecord::Migration[6.1]
  # List of all tables which contain non-user-generated data. Generated by
  # running the following query on a freshly-seeded database:
  #
  # SELECT table_name, TABLE_ROWS
  #   FROM INFORMATION_SCHEMA.TABLES
  #   WHERE TABLE_SCHEMA = 'dashboard_development' AND TABLE_ROWS > 0
  #   ORDER BY TABLE_ROWS DESC;
  #
  # Then manually removed a few tables, due to errors:
  #   levels: Timeout waiting for a response from the last query. (waited 30 seconds)
  #   level_sources: Column length too big for column 'data' (max = 16383); use BLOB or TEXT instead
  #   schools: There is a mismatch between the foreign key and primary key
  #     column types. Verify that the foreign key column type and the primary
  #     key of the associated table match types.
  #     Original message: Mysql2::Error: Referencing column 'school_id' and
  #     referenced column 'id' in foreign key constraint 'fk_rails_a0d64ecd35'
  #     are incompatible.
  TABLES = %w(
    activity_sections
    levels_script_levels
    script_levels
    parent_levels_child_levels
    lessons_resources
    lesson_activities
    level_concept_difficulties
    stages_standards
    resources
    objectives
    stages
    lessons_vocabularies
    vocabularies
    standards
    scripts_resources
    donor_schools
    lesson_groups
    lessons_programming_expressions
    reference_guides
    scripts
    schema_migrations
    videos
    plc_learning_modules
    course_versions
    course_offerings
    blocks
    programming_expressions
    course_scripts
    standard_categories
    unit_groups_resources
    learning_goal_evidence_levels
    google_sheets_shared_cdo_donors
    donors
    concepts_levels
    programming_methods
    plc_course_units
    data_docs
    unit_groups
    foorm_forms
    foorm_library_questions
    google_sheets_shared_cdo_languages
    games
    lessons_opportunity_standards
    libraries
    learning_goals
    programming_environment_categories
    foorm_libraries
    programming_classes
    callouts
    plc_courses
    secret_pictures
    shared_blockly_functions
    school_districts
    frameworks
    rubrics
    secret_words
    concepts
    programming_environments
    seed_info
    ar_internal_metadata
  )

  def up
    TABLES.each do |table|
      execute "ALTER TABLE #{table} CONVERT TO CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci"
    end
  end

  def down
    TABLES.each do |table|
      execute "ALTER TABLE #{table} CONVERT TO CHARSET utf8mb3 COLLATE utf8mb3_unicode_ci"
    end
  end
end
